# Generated by Django 3.1.7 on 2021-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('due_on', models.DateField(verbose_name='Deadline')),
                ('owner', models.CharField(max_length=255, verbose_name='Owner')),
                ('mark', models.BooleanField(default=False, verbose_name='Mark')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
